Add requirements ruby version
meilisearch/meilisearch-ruby pull request #132
Opened 2021-01-06 07:46 UTC by xluffy

2021-01-06 13:50 UTC, xluffy commented
For a job `Test / integration-tests`, I run in local PC, It works well. Not sure why.

```
bundle exec rspec ./spec/meilisearch/index/updates_spec.rb

MeiliSearch::Index - Updates
  gets an empty array when nothing happened before
  gets update status after adding documents
  gets all the update status
  waits for pending update with default values
  waits for pending update with default values after several updates
  waits for pending update with custom timeout_in_ms and raises MeiliSearchTimeoutError
  waits for pending update with custom interval_in_ms and raises Timeout::Error

Finished in 0.72082 seconds (files took 0.59354 seconds to load)
7 examples, 0 failures

Coverage report generated for RSpec to /Users/xluffy/code/meilisearch-ruby/coverage. 68 / 80 LOC (85.0%) covered.```

2021-01-12 10:49 UTC, curquiza requested changes
Thanks for adding this!! And sorry for the delay!

I request some changes in the README, otherwise, it looks ok! Thanks a lot!

2021-01-12 10:49 UTC, curquiza commented on README.md
> +
I would rather add a simple sentence.

"This package requires Ruby version 2.6.0 or later"

2021-01-12 10:49 UTC, curquiza commented on README.md
> +
I'm not sure this is useful in the README, this makes it too complex, and the README needs to stay simple 🙂

2021-01-13 03:38 UTC, xluffy commented
@curquiza Hey, I updated README now. Can you check again?

2021-01-13 09:53 UTC, curquiza approved these changes
Thanks a lot @xluffy!
And sorry again for the delay

bors merge

2021-01-13 10:32 UTC, curquiza commented
bors merge

2021-01-13 10:33 UTC, merged