Add typo tolerance customization settings
meilisearch/meilisearch-ruby pull request #350
Opened 2022-07-26 08:24 UTC by voloyev

# Pull Request

## What does this PR do?
Fixes #313 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-07-26 13:43 UTC, brunoocasali requested changes
Hello @voloyev, thanks a lot for your contribution!

I would like you to add some small things to make this PR perfect, do you mind?

Thanks for contributing with Meilisearch 👨‍🎤

2022-07-26 13:43 UTC, brunoocasali commented on spec/meilisearch/index/settings_spec.rb
> +    end
The `/typo-tolerance` sub-route does not respond with a task :)

```suggestion
    it 'gets default typo tolerance settings' do
      settings = index.typo_tolerance

      expect(settings).to eq(default_typo_tolerance)
    end
```

2022-07-26 13:43 UTC, brunoocasali commented on spec/meilisearch/index/settings_spec.rb
> +    end
```suggestion
    it 'resets typo tolerance settings' do
      update_task = index.update_typo_tolerance(new_typo_tolerance)
      client.wait_for_task(update_task['taskUid'])

      reset_task = index.reset_typo_tolerance
      client.wait_for_task(reset_task['taskUid'])

      expect(index.typo_tolerance).to eq(default_typo_tolerance)
    end
```

2022-07-26 13:43 UTC, brunoocasali commented on spec/meilisearch/index/settings_spec.rb
> +    end
```suggestion
    it 'updates typo tolerance settings' do
      update_task = index.update_typo_tolerance(new_typo_tolerance)
      client.wait_for_task(update_task['taskUid'])

      expect(index.typo_tolerance).to eq(new_typo_tolerance)
    end
```

2022-07-26 13:43 UTC, brunoocasali commented on lib/meilisearch/index.rb
> +      http_patch("/indexes/#{@uid}/settings/typo-tolerance", typo_tolerance_attributes)
A good addition here is to use the utility method to transform everything in camel case, so we can use snake_case in our ruby/rails apps :)

It should look like this:

```rb
    def update_typo_tolerance(typo_tolerance_attributes)
      attributes = Utils.transform_attributes(typo_tolerance_attributes)

      http_patch("/indexes/#{@uid}/settings/typo-tolerance", attributes)
    end
```

2022-07-26 13:45 UTC, voloyev commented
> Hello @voloyev, thanks a lot for your contribution!
> 
> 
> 
> I would like you to add some small things to make this PR perfect, do you mind?
> 
> 
> 
> Thanks for contributing with Meilisearch 👨‍🎤 

Hello! I'm do not mind☺️

2022-07-26 14:45 UTC, voloyev commented
@brunoocasali Do I need to squash the commits?

2022-07-26 16:58 UTC, brunoocasali commented
> @brunoocasali Do I need to squash the commits?

You can do it if you want, (I prefer to be honest), but it is not a requirement :)

2022-07-26 17:21 UTC, voloyev commented
> > @brunoocasali Do I need to squash the commits?
> 
> 
> 
> You can do it if you want, (I prefer to be honest), but it is not a requirement :) 

Will do then later today

2022-07-27 12:44 UTC, voloyev commented
> > > @brunoocasali Do I need to squash the commits?
> > 
> > 
> > You can do it if you want, (I prefer to be honest), but it is not a requirement :)
> 
> Will do then later today

Updated. Pls review

2022-07-27 14:19 UTC, brunoocasali approved these changes
Thank you for contributing with Meilisearch ❤️

2022-07-27 14:19 UTC, brunoocasali commented
bors merge

2022-07-27 14:21 UTC, merged