New await sync interface
meilisearch/meilisearch-ruby pull request #498
Opened 2023-10-09 11:04 UTC by ellnix

# Pull Request

## Related issue
Fixes #288

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

2023-10-12 15:46 UTC, ellnix commented
@brunoocasali this is pretty much complete, please feel free to review when you have (a lot of) time.

2023-10-16 10:56 UTC, ellnix commented
Rebased and force pushed.

2023-11-03 19:09 UTC, brunoocasali reviewed
Thanks a lot for your hard work here @ellnix amazing!

I am asking for some changes but it is nothing to be worried about!

2023-11-03 20:03 UTC, brunoocasali requested changes
Amazing work @ellnix I think we could make some small modifications, but I was impressed, very good work!

2023-11-29 12:07 UTC, ellnix commented
@brunoocasali sorry for taking so long to get back to this. I addressed your feedback and rebased it to main (for the changes since you last reviewed it, start at commit [b141ed4](https://github.com/meilisearch/meilisearch-ruby/pull/498/commits/b141ed48198449090f93ede4d7281ae65b01960b)).

2023-12-11 20:50 UTC, brunoocasali commented
let's see if the code coverage will still be broken now!

Also, can you squash the commits @ellnix ?

2023-12-11 22:24 UTC, ellnix commented
> Also, can you squash the commits @ellnix ?

Squash them into a single commit or just fewer commits? How many commits would you consider ideal? The history might be a little bit hard to follow if only a few commits had +1800 -1200 changes.

2023-12-14 02:49 UTC, brunoocasali commented on lib/meilisearch/utils.rb
> +        logger.warn(message)
> I took the liberty to unify the warning logging with a Rails-like logger. 

Good for me!

`MeiliSearch.logger` is better indeed!

2023-12-14 02:53 UTC, brunoocasali commented
> Squash them into a single commit or just fewer commits? How many commits would you consider ideal? The history might be a little bit hard to follow if only a few commits had +1800 -1200 changes.

A few commits would be great. I don't have a number for that, it is more a feeling than anything. If you squash them based on the group like, you did a lot of the same but in multiple files, so in my mind you would have a single commit of that "theme".

2024-01-10 10:30 UTC, ellnix commented
@brunoocasali should be ready for merge, unless you want me to squash it down further.

2024-02-14 16:48 UTC, brunoocasali commented on spec/meilisearch/models/task_spec.rb
> +        expect(subject).not_to have_received(:refresh)
When I mention the xUnit I mean this:

```suggestion
        allow(subject).to receive(:refresh)
        
        subject.enqueued?
        
        expect(subject).not_to have_received(:refresh)
```

2024-02-14 16:51 UTC, brunoocasali approved these changes
Looks good to me, let get this merged @ellnix

Thanks a lot for all the hard work in this repo @ellnix ❤️

2024-02-16 17:28 UTC, ellnix commented
I'm not sure this will work, but addressing the conflict with a commit might dismiss the approval review.

bors merge

2024-02-16 17:51 UTC, ellnix commented
Give me a second with this, apparently the git pull on my fork didn't go through properly and now everything is messed up.

2024-02-16 18:08 UTC, ellnix commented
Well I fixed the git history and force pushed. Sorry about the issues but I don't think there was a way for me to resolve the main conflicts without automatically dismissing the approval review (even when I tried a merge rather than a rebase).

I looked it up, it seems to be a setting (https://github.com/isaacs/github/issues/783#issuecomment-320211882) but it does not look like it would be a good idea, since it would allow someone with approval to push arbitrary code and then choose to merge.

2024-02-27 19:31 UTC, brunoocasali approved these changes
LGTM!

2024-02-27 19:40 UTC, ellnix commented
bors merge

2024-02-27 19:42 UTC, merged