Clarify the ruby version
meilisearch/meilisearch-ruby pull request #534
Opened 2024-05-10 17:47 UTC by brunoocasali

Addressing this comment: https://github.com/meilisearch/meilisearch-ruby/pull/533#issuecomment-2099072353

2024-05-10 17:52 UTC, ellnix requested changes
I like the idea, just a suggestion to make the promise a little bit more precise.

2024-05-10 17:52 UTC, ellnix commented on README.md
> +We officially support any version of Ruby that is still being officially maintained, but in any case, you can use any version above Ruby 3.0.
```suggestion
We officially support any version of Ruby that is still receiving at least [security maintenance](https://www.ruby-lang.org/en/downloads/branches/). You may, however, be fine with any Ruby version above 3.0.
```

2024-05-14 17:25 UTC, ellnix approved these changes
LGTM.

2024-05-15 11:41 UTC, brunoocasali commented
bors merge

2024-05-15 11:42 UTC, merged